Add preferred layout name for new product page
Voog/design-dusseldorf pull request #105
Opened 2021-03-17 10:11 UTC by robertpih

Related to #104

2021-05-19 10:56 UTC, siimha approved these changes

2021-05-19 13:33 UTC, siimha requested changes
[Siin](https://github.com/Voog/design-dusseldorf/blob/master/components/submenu.tpl#L15) ka veel puudu

2021-05-26 06:33 UTC, tanelj approved these changes

2021-06-09 10:38 UTC, tanelj requested changes
Menüü toimib korrektselt, kuid mõned kõrvalteemad leidsin.

2021-06-09 10:38 UTC, tanelj commented on components/submenu_for_current.tpl
>  {% if editmode or page.menuitem.children? %}
Siin jääv preview vaates tühi `<nav class="sub-menu"><ul>` . Ka siin oleks korrektsem capturiga sisu püüda ja if `sisu != blank` kontrollida.

2021-06-09 10:38 UTC, tanelj commented on components/menu-level-1-link.tpl
> +  <a class="{% if item.selected? %}active{% endif %}{% unless item.translated? %}fci-editor-menuadd untranslated{% endunless %}" href="{{ item.url }}">{{ item.title }}</a>
Võimalik, et see oli juba enne, kuid tõlkimata menuitemitel puudub stiil (või pole see korrektne) ja tõlkimata itemid ei eristu tõlgitutest. Võiks ka siin korda saada.

2021-06-11 13:44 UTC, tanelj approved these changes

2021-06-14 08:30 UTC, siimha approved these changes
Naiss!

2021-06-16 13:18 UTC, merged