Add blog & article settings
Voog/design-dusseldorf pull request #107
Opened 2021-06-11 11:10 UTC by pxska

2021-06-14 09:29 UTC, tanelj requested changes
Funktsionaalsus on kena, kuid veidi tagasisidet seoses JS'iga.

Semikoolonid (https://flaviocopes.com/javascript-automatic-semicolon-insertion/, https://flaviocopes.com/javascript-automatic-semicolon-insertion/)

Ja tüübikontrolliga võrdlusega seoses (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness)

2021-06-14 09:29 UTC, tanelj commented on components/settings-article-page.tpl
> +      show_comments = Boolean(articleDataValues.show_comments)
Semikoolon puudub lõpus.

2021-06-14 09:29 UTC, tanelj commented on components/settings-article-page.tpl
> +      show_comments = Boolean(globalDataValues.show_comments)
Semikoolon puudub lõpus.

2021-06-14 09:29 UTC, tanelj commented on components/settings-article-page.tpl
> +      show_date = Boolean(articleDataValues.show_date)
Semikoolon puudub lõpus.

2021-06-14 09:29 UTC, tanelj commented on components/settings-article-page.tpl
> +      show_date = Boolean(globalDataValues.show_dates)
Semikoolon puudub lõpus.

2021-06-14 09:29 UTC, tanelj commented on components/settings-blog-page.tpl
> +      show_comments = Boolean(globalDataValues.show_comments)
Semikoolon puudub lõpus.

2021-06-14 09:29 UTC, tanelj commented on components/settings-blog-page.tpl
> +      show_dates = Boolean(globalDataValues.show_dates)
Semikoolon puudub lõpus.

2021-06-14 09:29 UTC, tanelj commented on components/settings-blog-page.tpl
> +          } else if (data.show_dates == false) {
Siin ja ees pool oleks õige kasutada [tüübikontrolliga võrdlust](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness) `data.show_dates === false`:

Sest ka 

```
"" == false
=> true
```

2021-06-14 09:29 UTC, tanelj commented on components/settings-editor.tpl
> +        });;
Topelt semikoolon.

2021-06-14 09:29 UTC, tanelj commented on components/settings-editor.tpl
> +          $('.edy-settings-editor-inner-title').text($(this).find('.edy-cbtn-content .p14.bold').text())
Semikoolon puudub.

2021-06-14 09:29 UTC, tanelj commented on sources/javascripts/concat/editmode/editmode.js
> +            })
Semikoolon puudub.

2021-06-14 11:04 UTC, siimha requested changes
Mõned errorid jäid silma.

2021-06-14 11:04 UTC, siimha commented on javascripts/editmode.js
> +window.site = $.extend(window.site || {}, {
Kuna kasutad siin `window.site` nimeskoopi, siis sellest tulenevalt annab `template.bindContentItemImgDropAreas(...)` errori.

2021-06-14 11:04 UTC, siimha commented on sources/javascripts/concat/main.js
>    window.template = $.extend(window.template || {}, {
Kuna juba refaktooringuks läks, siis võiksid siin ka kokku tõmmata ehk kasutada ühte nimeskoopi ja eemaldada välja kommenteeritud funktsioonid, mida pole olemas (`initCommonPage` jne).

2021-06-16 09:02 UTC, siimha requested changes

2021-06-16 09:02 UTC, siimha commented on layouts/blog___news.tpl
>    {% include "edicy-tools" %}
See on `settings-popover` komponendis juba includitud.

2021-06-16 09:02 UTC, siimha commented on layouts/blog_article.tpl
>    {% include "edicy-tools" with "post_page" %}
See on settings-popover komponendis juba includitud.

2021-06-16 09:02 UTC, siimha commented on Gruntfile.js
> +      editmode: {
editmode puhul ei toimi grunt watch, kuna ei sihi seda alamkausta ja task on vaid `concat:build`i pihta. Parandus:
```
js_concat: {
  files: ['sources/javascripts/concat/*.js', 'sources/javascripts/concat/editmode/*.js'],
  tasks: ['concat', 'uglify:build', 'exec:kitmanifest', 'exec:kit:javascripts/*.js']
}
```

2021-06-16 09:02 UTC, siimha commented on components/edicy-tools.tpl
>      site.toggleFlags();
Kuna seda componenti lisatakse 2x, siis näitek see funktsioon tühistab soovitud käitumist ehk vahetab samale tagasi.

2021-06-17 11:39 UTC, siimha commented
Lahenda ka manifesti ja cssi konfliktid.

2021-06-25 12:42 UTC, siimha requested changes

2021-06-25 12:42 UTC, siimha commented on components/edicy-tools.tpl
> +          site.contentHalfBgPreview(data, '.js-content-left', contentHalfLeftBg);
See funktsioon on `template` nimeskoobis. Ühtlusta editmode ja main scriptis window objektide võtmed. Näiteks mõlemale`window.site = $.extend(window.site || {}, { ...`.

2021-07-27 12:52 UTC, tanelj requested changes
Üks blokker viga manifestis, mis takistab CB'sse importi ja testi.

2021-07-27 12:52 UTC, tanelj commented on manifest.json
> -      "file": "layouts/front_page.tpl",
Manifest on hetkel katki läinud. `front_page` kadus manifestist ära ning "common page" on kaks korda

2021-07-27 13:24 UTC, tanelj requested changes
Artikli pool toimin nagu peab, kuid regressioon on toiminud (ilmselt seoses editmode.js'iga?), kus:

* [ ] Toote listis (ja tootelehel) näidatakse kogu aeg, muutmise vaates itemitel loaderit. Nii pildita kui pildiga itemitel jääb `not-loaded` klass külge.

2021-07-30 08:38 UTC, tanelj approved these changes
Kena!

2021-07-30 10:13 UTC, merged