Kaufhaus kaboom
Voog/design-dusseldorf pull request #80
Opened 2017-12-08 14:43 UTC by SSirjes

2018-01-25 10:17 UTC, siimha commented
* [ ] Ostukorvi nupul puudub ümbris ja hover
http://recordit.co/XchTNC3hqb

2018-01-25 11:23 UTC, siimha commented
* [ ] Nime ja e-maili lahtrid ei ole kommentaari sisestamisel samal tasemel
![screen shot 2018-01-25 at 13 20 14 2](https://user-images.githubusercontent.com/35253483/35385968-e347ede2-01d2-11e8-8c9d-b9bd1fa8cca3.png)

2018-01-30 11:43 UTC, SSirjes commented
* [ ] kui muuta product list mall product malliks, siis ei kuvata alamlehti.

2018-02-09 08:00 UTC, SSirjes commented
Add empty content area for "Product list" layout.
Add search

2018-02-12 09:05 UTC, SSirjes commented
* [ ] tühja sisuala ei tohi kuvada

2018-02-13 10:53 UTC, siimha commented
[ ] Määrates toote malli esileheks, puudub seadistamise võimalus
<img width="457" alt="screen shot 2018-02-13 at 12 53 11" src="https://user-images.githubusercontent.com/35253483/36146301-e536882c-10bc-11e8-8b16-252a608a543c.png">

2018-02-16 13:26 UTC, SSirjes commented
* [ ] kui alamenüü on tühi, siis ei tohiks tphja plokki kuvada

2018-02-19 11:49 UTC, SSirjes commented
* [ ] kontrolli manifest failis üle, kas on olemas layout_name: page_default ja front_page layout_name: page_front

![screen shot 2018-02-19 at 13 47 56](https://user-images.githubusercontent.com/13623224/36376366-8340c8a8-157b-11e8-833f-ca84c0745dae.png)

2018-02-19 12:26 UTC, siimha commented
* [ ] variatsiooni valiku väljal ei muutu boarder color sarnaselt buy buttoni värviga (värvi koodid var(--color-dark) / var(--color-light))
<img width="539" alt="screen shot 2018-02-19 at 14 21 47" src="https://user-images.githubusercontent.com/35253483/36377604-6eb9cbf0-1580-11e8-8ee7-4eb0d410c3d5.png">

2018-02-19 12:59 UTC, siimha commented
* [ ] 600px peal muutub form_field_select laius 100% !important peale, kuid teistel mallidel jääb fikseeritult sama laiusega.
<img width="1406" alt="screen shot 2018-02-19 at 14 55 10" src="https://user-images.githubusercontent.com/35253483/36378972-8a3ce95c-1585-11e8-94d1-2a74bd4aeb6f.png">

2018-02-19 13:54 UTC, siimha commented
Näiteks Anchoragel on custom-btn :hover {
  -webkit-transition: 500ms;
  -o-transition: 500ms;
  transition: 500ms;

http://recordit.co/cgvAHaQtu7

2018-02-19 14:16 UTC, siimha commented
Crop nupul outline sinine ja lahendus: 
 .bg-crop-btn {  
     &:focus {
        outline: 0;
     }
}
<img width="239" alt="screen shot 2018-02-19 at 16 12 56" src="https://user-images.githubusercontent.com/35253483/36382006-31776ada-1590-11e8-8b8d-f071fefc4ed7.png">

2018-02-20 08:19 UTC, SSirjes commented
* [x] check buy button variants style on other layouts (common page, front page)

2018-02-22 08:54 UTC, siimha commented
* [ ] Muuta blog_article.scss faili nimetus (nt. product.scss)
* [ ] Content-item.scss faili sisu on juba blog_article.scss failis olemas

2018-02-22 11:42 UTC, siimha commented
* [ ] Tausta muutmise nupp on product ja product listi vaates madalamal, kui teistel lehtedel.

Front/Common/Blog:
<img width="427" alt="screen shot 2018-02-22 at 13 36 26" src="https://user-images.githubusercontent.com/35253483/36536597-33678c56-17d6-11e8-9c41-964afc527fe6.png">

Product/Product list:
<img width="451" alt="screen shot 2018-02-22 at 13 36 39" src="https://user-images.githubusercontent.com/35253483/36536602-3dc70cbc-17d6-11e8-9e72-dad9d9bcc385.png">

2018-02-22 11:50 UTC, siimha commented
* [ ] Mina kaotaksin Product listi vaates ülemise alamlehe lisamise nupu.
<img width="887" alt="screen shot 2018-02-22 at 13 47 01" src="https://user-images.githubusercontent.com/35253483/36536950-5d1f028a-17d7-11e8-838d-b5a2686bbc18.png">

2018-02-22 13:28 UTC, siimha commented
* [ ] main.scss-is peaks loaderiga seotud koodi stiili muutma. Line 2689-2759 tuleks üle vaadata.
Võiks olla selline: 
<img width="337" alt="screen shot 2018-02-22 at 15 26 13" src="https://user-images.githubusercontent.com/35253483/36540960-fd951f76-17e4-11e8-84c3-3be7ef152e03.png">
Ja Grunt ise muudab main.css-is selliseks:
<img width="480" alt="screen shot 2018-02-22 at 15 25 54" src="https://user-images.githubusercontent.com/35253483/36540972-075cc734-17e5-11e8-8795-61a775fe6ea6.png">

2018-03-01 11:37 UTC, SSirjes commented
* [ ] comment in <script src="{{ javascripts_path }}/application.min.js"></script>

2018-03-02 13:59 UTC, siimha commented
Hoveriga kaob osta nupul boarder ära http://recordit.co/UqMkb6NZpj. Mina lahendasin selle järgnevalt (kuigi !important pole just parim lahendus):
<img width="398" alt="screen shot 2018-03-02 at 15 57 51" src="https://user-images.githubusercontent.com/35253483/36902281-9bdd07ea-1e32-11e8-95c5-00cde79cfe50.png">

2018-03-02 14:34 UTC, siimha commented
Lisaksin ka form_field_label klassile var(--color-dark) siis muutuvad sarnaselt ostunupu ja form_field_select värviga. Anchoragel ka sarnane loogika http://recordit.co/up5fwE2adG

2018-03-06 08:33 UTC, siimha commented
* [ ] Add CDN for Lazyload (hetkel oled sa Lazyloadi vist otse kopeerinud main.js faili, sest seda ei ole bower componentide all). Realtes https://github.com/Edicy/operations/issues/259 ja lahendus sarnaselt Anchoragele https://github.com/Voog/design-anchorage/pull/285

2018-03-07 09:51 UTC, SSirjes commented
* [ ] test design editor

2018-03-09 08:00 UTC, SSirjes commented
* [ ] Product list > product placeholder should be white with dark background

![screen shot 2018-03-09 at 09 20 23](https://user-images.githubusercontent.com/13623224/37195348-21c5f5a4-237b-11e8-828d-d59b0b652a6f.png)

* [ ] remove white border around product image if product list page has dark background

![screen shot 2018-03-09 at 09 56 38](https://user-images.githubusercontent.com/13623224/37196733-a54e7612-2380-11e8-9fab-9d80216cbe2e.png)

2018-03-11 16:37 UTC, SSirjes commented
* [ ] List layout submenu should only display under product list page.

2018-03-12 13:08 UTC, siimha commented
form_field_selectile rakendub background-color, mis ei paista läbi ja ico-arrowd pole paista, lahendada võiks nt nii:
    .dark-background & {
      background-color: rgba($white, .1);
      background-image: url('../assets/ico-arrow-white.svg');
    }

    .light-background & {
      background-color: rgba($black, .01);
      background-image: url('../assets/ico-arrow.svg');
    }

2018-03-16 13:02 UTC, SSirjes commented
* [ ] remove unnecessary classes

2018-03-19 06:07 UTC, SSirjes commented
* [ ] disconnect design editor and button text font-size

2018-03-19 14:20 UTC, siimha commented
* [ ] Change content-item-box .with-image background background-color opacity to something lower

2018-03-20 14:00 UTC, SSirjes commented
* [ ] comment in <script src="{{ javascripts_path }}/application.min.js"></script>
* [ ] manifest fail üle vaadata

2018-03-22 13:58 UTC, mikkpr requested changes
Leidsin paar mõtlemise kohta. Sisuliselt on kõik õige, aga lihtsalt kordust võiks võimalusel vältida.

2018-03-22 13:58 UTC, mikkpr commented on components/submenu.tpl
> +  {% for item in site.all_menuitems_on_level_2 %}
Siin ja allpool on hästi palju kordust, millest võiks lahti saada:
```
{% for i in (2..4) %}
  {% assign level_str = 'all_menuitems_on_level_' | append: i %}
  {% for item in site[level_str] %}
    {% if item.selected? and page.level == i | plus: 1  %}
      {% if editmode or item.children? %}
        {% if item.layout_title == 'Product' or item.layout_title == 'Product list' %}
          <ul>
            {% for child in item.visible_children %}
              {% if exclude_products == true and child.layout_title != 'Product' and child.layout_title != "Product list" %}
                <li><a href="{{child.url}}"{% if child.selected? %} class="active"{% endif %}{% unless child.translated? %} class="untranslated fci-editor-menuadd"{% endunless %}>{{child.title}}</a></li>
                {% elsif exclude_products != true %}
                <li><a href="{{child.url}}"{% if child.selected? %} class="active"{% endif %}{% unless child.translated? %} class="untranslated fci-editor-menuadd"{% endunless %}>{{child.title}}</a></li>
              {% endif %}
            {% endfor %}
          </ul>
        {% endif %}
      {% endif %}
    {% endif %}
  {% endfor %}
{% endfor %}
```

Kindlasti peaks läbi testima, aga nii palju kui ise vaatasin, tundus toimivat küll ja on samaväärne kui see praegune variant, kus muutub ainult number.

2018-03-22 13:58 UTC, mikkpr commented on layouts/product.tpl
> +    <script type="text/javascript">
Ma arvan, et need custom styled peaks defineerima igas mallis ning kogu see jupp võiks olla kas `javascripts` komponendis või täitsa eraldi komponendis ning layoutides kasutama siis `{% include 'custom-styles' %}` või midagi taolist.

2018-03-23 11:40 UTC, siimha commented on components/submenu.tpl
> +  {% for item in site.all_menuitems_on_level_2 %}
Testin sinu lahenduse üle.

2018-03-23 16:05 UTC, siimha commented on components/submenu.tpl
> +  {% for item in site.all_menuitems_on_level_2 %}
Tegin väikese paranduse ja commitisin ära

2018-03-23 16:22 UTC, siimha commented on layouts/product.tpl
> +    <script type="text/javascript">
Võtsin scripti layouts failidest ja panin javascript.tpl faili, mis on juba includitud layouts failidesse. Tegin ka commiti.

2018-03-28 11:01 UTC, mikkpr approved these changes

2018-04-11 12:42 UTC, merged